ERROR:root:An error occurred in file 'tg_assistent_py.py', line 90: 'Close'
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/PUMP_SKREENER/tg_assistent_py.py", line 85, in squeeze_unMomentum_assignator
    m15_data = await self.squeeze_unMomentum(m15_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/PUMP_SKREENER/TECHNIQUES/techniques_py.py", line 14, in squeeze_unMomentum
    df['20sma'] = df['Close'].rolling(window=20).mean()
                  ~~^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/PUMP_SKREENER/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/PUMP_SKREENER/.venv/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'Close'
